## 00. Pytorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## Introduction to Tensors

> Indented block



### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of ransom numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> looks at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors = https://pytorch.org/docs/stable/generated/torch.rand.html


In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0626, 0.3240, 0.8074, 0.7090],
        [0.9263, 0.6200, 0.8570, 0.4790],
        [0.2821, 0.5035, 0.5931, 0.2878]])

In [17]:
# Create a random tensor with a similar shape ot an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [21]:
# Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatpyes is one of the 3 big errors you'll run into with PyTorch & deep learning:
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on the right device

In [23]:
# Float  32 tensor
float_32_tensor = torch.tensor([3, 6, 0],
                               dtype= torch.float32, # what datatype is the tensor (e.g float32 or float16))
                               device= None, # What device is your tensor on?
                               requires_grad= False) # Whether or not to track gradients with this tensors operations?
float_32_tensor

tensor([3., 6., 0.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 0.], dtype=torch.float16)

In [26]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

### Getting information from tensors (tensor attributes)

  1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
  2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
  3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [27]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7486, 0.2840, 0.1569, 0.4441],
        [0.8505, 0.0595, 0.0557, 0.2643],
        [0.5722, 0.3193, 0.4977, 0.8811]])

In [28]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.dtype}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7486, 0.2840, 0.1569, 0.4441],
        [0.8505, 0.0595, 0.0557, 0.2643],
        [0.5722, 0.3193, 0.4977, 0.8811]])
Datatype of tensor: torch.float32
Shape of tensor: torch.float32
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [29]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [30]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [31]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [32]:
# Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [33]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1.   Element-wise multiplication
2.   Matrix multiplication

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner** dimensions need to match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2, 3) -> (3, 3)`


In [34]:
# Element wise multiplication
print(tensor, "*",tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [35]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [36]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [37]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]* tensor[i]
print(value)

tensor(14)
CPU times: user 492 µs, sys: 88 µs, total: 580 µs
Wall time: 589 µs


In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 28 µs, sys: 0 ns, total: 28 µs
Wall time: 31.2 µs


tensor(14)

### One of the most common errors in deep learning: Shape Errors

In [39]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B) $ torch.mm is the same as torch.matmul
# torch.matmul(tensor_A, tensor_B)

In [40]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.
A **transpose** switches the axes of the dimensions of a given tensor.

In [41]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]), torch.Size([3, 2]))

In [42]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [43]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print ("Output: \n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\n Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 Output shape: torch.Size([3, 3])


In [44]:
list1 = [1, 2, 3]
list2 = [3, 4, 5]
list3 = [6, 7, 8]

torch.tensor([list1,
              list2,
              list3])

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [45]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [46]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [47]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [48]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [49]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

###Finding the positional min and max

In [50]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [51]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keeps the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze - Add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped in a certain way)

In [52]:
# Let's create a tensor

import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [53]:
# Add an extra dimenesion
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [56]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
# torch.squeeze() - remove all single dimensions from a target sensor
print(f"Previous reshaped tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous reshaped tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [58]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specigic dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [59]:
# torch.permute - rearranges the dimensions of a target tensor in a specific order
x_original = torch.rand(size=(224, 224, 3)) #[height, widdth, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"\nNew shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])

New shape: torch.Size([3, 224, 224])


In [60]:
x_original[0, 0, 0] = 732724
x_original[0, 0, 0], x_permuted[0, 0, 0]


(tensor(732724.), tensor(732724.))

### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [61]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [62]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [63]:
# Let's index on the middle bracket (dim=1)
x[0, 0], x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [64]:
# Let's index on the most inner backet (last dimension)
x[0][0][0], x[0, 0, 0]

(tensor(1), tensor(1))

In [65]:
x[0, 1, 1]

tensor(5)

In [66]:
 # You can also use ":" to select "all" of a target dimension
 x[:, 0]

tensor([[1, 2, 3]])

In [67]:
# Get all values of the 0th and 1st dimensions but only index 1 of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [68]:
# Get all values of the 0th dimension but onl the 1 index value the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [69]:
# Get index 0 of the 0th and 1st dimension and all values of 2nd dimension.
x[0, 0, :]

tensor([1, 2, 3])

In [70]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [71]:
# Index on x to return [3, 6, 9]
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

Numpy is a popular scientific Python numerical computing library.

Because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [72]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [73]:
array.dtype

dtype('float64')

In [74]:
tensor.dtype

torch.float64

In [75]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [76]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)
As you learn more about neural netowrks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) os the randomness they create are simulated randomness (though there is debate on this too, but since I'm no a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to imporve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

`start with random numbers -> tensor operations -> try to make better (again and again and again)`

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments. For example, you create an algorithm capable of achieving X performance. And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where **reproducibility** comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them ot be different right?

In [77]:
import torch

# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A: \n{random_tensor_A}\n")
print(f"Tensor B: \n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere?)")
random_tensor_A == random_tensor_B

Tensor A: 
tensor([[0.5282, 0.0462, 0.4196, 0.2947],
        [0.3525, 0.4084, 0.0341, 0.0808],
        [0.5899, 0.2598, 0.1839, 0.4089]])

Tensor B: 
tensor([[0.7212, 0.5876, 0.8515, 0.8150],
        [0.8443, 0.8810, 0.0019, 0.0621],
        [0.1520, 0.0330, 0.9182, 0.5401]])

Does Tensor A equal Tensor B? (anywhere?)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Just as you might've expected, the tensors come out with different values.

But what if you wanted to create two random tensors with the same values. As in, the tensors would still contain random values, but they would be of the same flavour.

That's where `torch.manual_seed(seed)` comes in, where `seed` is an integer (like `42` but it could be anything) that flavours the randomness.

Let's try it out by creating some more *flavoured* random tensors.

In [78]:
import torch
import random

# Set the random seed
RANDOM_SEED = 69
torch.manual_seed(seed = RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C

torch.manual_seed(seed = RANDOM_SEED)
random_tensor_D = torch.rand(3,4)



print(f"Tensor C: \n{random_tensor_C}\n")
print(f"Tensor D: \n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere?)")
random_tensor_C == random_tensor_D

Tensor C: 
tensor([[0.8398, 0.8042, 0.1213, 0.5309],
        [0.6646, 0.4077, 0.0888, 0.2429],
        [0.7053, 0.6216, 0.9188, 0.0185]])

Tensor D: 
tensor([[0.8398, 0.8042, 0.1213, 0.5309],
        [0.6646, 0.4077, 0.0888, 0.2429],
        [0.7053, 0.6216, 0.9188, 0.0185]])

Does Tensor C equal Tensor D? (anywhere?)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [79]:
!nvidia-smi

Sun Feb 19 11:25:23 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P0    31W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

##Exercises

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on `torch.Tensor` and for `torch.cuda`.

From `torch.Tensor`:
* `Tensor.T` returns a view of this tensor with its dimensions reversed.
* `Tensor.H` returns a view of a matrix (2D tensor) conjugated and transposed.
* `Tensor.mT` returns a view of this tensor with the last two dimensions transposed.
* `Tensor.mH` Accessing this property is equivalent to calling `adjoint()`.

For more:
https://pytorch.org/docs/stable/tensors.html#id4

For info on cuda: https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics

2. Create a random tensor with shape `(7, 7)`.

In [80]:
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.8741, 0.0560, 0.9659, 0.0073, 0.3628, 0.4197, 0.6444],
        [0.0099, 0.5925, 0.9631, 0.6958, 0.9157, 0.5523, 0.2344],
        [0.3262, 0.4521, 0.7020, 0.6274, 0.0945, 0.8525, 0.3572],
        [0.7492, 0.3579, 0.5453, 0.8171, 0.0570, 0.4560, 0.0183],
        [0.5854, 0.6620, 0.0158, 0.5309, 0.9056, 0.6011, 0.6072],
        [0.5147, 0.7654, 0.5434, 0.3774, 0.3056, 0.6771, 0.3802],
        [0.2426, 0.8268, 0.8742, 0.6367, 0.3849, 0.0412, 0.8489]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [81]:
random_tensor2 = torch.rand(1, 7)
torch.matmul(random_tensor,random_tensor2.T)

tensor([[1.6949],
        [1.6667],
        [1.3519],
        [1.2671],
        [2.3343],
        [1.8517],
        [2.1346]])

4. Set the random seed to `0` and do exercises 2 & 3 over again.

In [82]:
RANDOM_SEED = 0
torch.manual_seed(seed = RANDOM_SEED)
random_tensor = torch.rand(7,7)
random_tensor2 = torch.rand(1,7)

torch.matmul(random_tensor, random_tensor2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one). If there is, set the GPU random seed to `1234`.

In [83]:
torch.cuda.manual_seed(1234)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [86]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device} ")

tensor_A = torch.rand(size = (2,3)).to(device)
tensor_B = torch.rand(size = (2,3)).to(device)

tensor_A, tensor_B

Device: cuda 


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [91]:
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7.

In [94]:
max = tensor_C.max()
min = tensor_C.min()

max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

9. Find the maximum and minimum index values of the output of 7.

In [96]:
argmax = tensor_C.argmax()
argmin = tensor_C.argmin()

argmax, argmin

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor  with all the 1 dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [99]:
torch.manual_seed(7)

tensor_10 = torch.rand(1, 1, 1, 10)



tensor_10_squeeze = tensor_10.squeeze()

tensor_10, tensor_10_squeeze


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))